call code --install-extension christian-kohler.npm-intellisense 
call code --install-extension DavidAnson.vscode-markdownlint 
call code --install-extension dbaeumer.vscode-eslint 
call code --install-extension eg2.vscode-npm-script 
call code --install-extension isudox.vscode-jetbrains-keybindings 
call code --install-extension KnisterPeter.vscode-github 
call code --install-extension trinm1709.dracula-theme-from-intellij 
call code --install-extension christian-kohler.npm-intellisense 
call code --install-extension DavidAnson.vscode-markdownlint 
call code --install-extension dbaeumer.vscode-eslint 
call code --install-extension eg2.vscode-npm-script 
call code --install-extension isudox.vscode-jetbrains-keybindings 
call code --install-extension KnisterPeter.vscode-github 
call code --install-extension Shan.code-settings-sync 
call code --install-extension trinm1709.dracula-theme-from-intellij 
